# These are supported funding model platforms

github: [masterenderman, al132]
patreon: _masterenderman_
custom: [https://streamlabs.com/endermanwhosearchthebeast, https://www.twitch.tv/endermanwhosearchthebeast]
